module.exports = [
[
  {pid: 0x00, text: "List of PIDs supported (range 01 to 32)"},
  {pid: 0x01, text: "Status since the last clearing of fault codes"},
  {pid: 0x02, text: "Fault code that caused the recording of \"freeze frame\" data"},
  {pid: 0x03, text: "Fuel system status"},
  {pid: 0x04, text: "Engine load calculated in %"},
  {pid: 0x05, text: "Temperature of the engine coolant in Â°C"},
  {pid: 0x06, text: "Short-term fuel % trim bank 1"},
  {pid: 0x07, text: "Long-term fuel % trim bank 1"},
  {pid: 0x08, text: "Short-term fuel % trim bank 2"},
  {pid: 0x09, text: "Long-term fuel % trim bank 2"},
  {pid: 0x0A, text: "Fuel pressure in kPa"},
  {pid: 0x0B, text: "Intake manifold absolute pressure in kPa"},
  {pid: 0x0C, text: "Engine speed in rpm"},
  {pid: 0x0D, text: "Vehicle speed in kph"},
  {pid: 0x0E, text: "Timing advance on cylinder 1 in degrees"},
  {pid: 0x0F, text: "Intake air temperature in Â°C"},
  {pid: 0x10, text: "Air flow measured by the flowmeter in g/s"},
  {pid: 0x11, text: "Throttle position in %"},
  {pid: 0x12, text: "Status of the secondary intake circuit"},
  {pid: 0x13, text: "O2 sensor positions bank/sensor"},
  {pid: 0x14, text: "Oxygen sensor volts bank 1 sensor 1/td>"},
  {pid: 0x15, text: "Oxygen sensor volts bank 1 sensor 2"},
  {pid: 0x16, text: "Oxygen sensor volts bank 1 sensor 3"},
  {pid: 0x17, text: "Oxygen sensor volts bank 1 sensor 4"},
  {pid: 0x18, text: "Oxygen sensor volts bank 2 sensor 1"},
  {pid: 0x19, text: "Oxygen sensor volts bank 2 sensor 2"},
  {pid: 0x1A, text: "Oxygen sensor volts bank 2 sensor 3"},
  {pid: 0x1B, text: "Oxygen sensor volts bank 2 sensor 4"},
  {pid: 0x1C, text: "OBD computer specification"},
  {pid: 0x1D, text: "O2 sensor positions bank/sensor"},
  {pid: 0x1E, text: "Auxiliary input status"},
  {pid: 0x1F, text: "Run time since engine start"},
  {pid: 0x20, text: "List of PIDs supported (range 33 to 64)"},
  {pid: 0x21, text: "Distance travelled with MIL on in kms"},
  {pid: 0x22, text: "Relative fuel rail pressure in kPa"},
  {pid: 0x23, text: "Fuel rail pressure in kPa"},
  {pid: 0x24, text: "O2 sensor (extended range) bank 1, sensor 1 (lambda and volts)"},
  {pid: 0x25, text: "O2 sensor (extended range) bank 1, sensor 2 (lambda and volts)"},
  {pid: 0x26, text: "O2 sensor (extended range) bank 1, sensor 3 (lambda and volts)"},
  {pid: 0x27, text: "O2 sensor (extended range) bank 1, sensor 4 (lambda and volts)"},
  {pid: 0x28, text: "O2 sensor (extended range) bank 2, sensor 1 (lambda and volts)"},
  {pid: 0x29, text: "O2 sensor (extended range) bank 2, sensor 2 (lambda and volts)"},
  {pid: 0x2A, text: "O2 sensor (extended range) bank 2, sensor 3 (lambda and volts)"},
  {pid: 0x2B, text: "O2 sensor (extended range) bank 2, sensor 4 (lambda and volts)"},
  {pid: 0x2C, text: "EGR in %"},
  {pid: 0x2D, text: "EGR error in %"},
  {pid: 0x2E, text: "Evaporation purge in %"},
  {pid: 0x2F, text: "Fuel level in %"},
  {pid: 0x30, text: "Number of warning(s) since faults (DTC) were cleared"},
  {pid: 0x31, text: "Distance since faults (DTC) were cleared."},
  {pid: 0x32, text: "Evaporation system vapour pressure in Pa"},
  {pid: 0x33, text: "Barometic pressure in kPa"},
  {pid: 0x34, text: "O2 sensor (extended range) bank 1, sensor 1 (lambda and volts)"},
  {pid: 0x35, text: "O2 sensor (extended range) bank 1, sensor 2 (lambda and volts)"},
  {pid: 0x36, text: "O2 sensor (extended range) bank 1, sensor 3 (lambda and volts)"},
  {pid: 0x37, text: "O2 sensor (extended range) bank 1, sensor 4 (lambda and volts)"},
  {pid: 0x38, text: "O2 sensor (extended range) bank 2, sensor 1 (lambda and volts)"},
  {pid: 0x39, text: "O2 sensor (extended range) bank 2, sensor 2 (lambda and volts)"},
  {pid: 0x3A, text: "O2 sensor (extended range) bank 2, sensor 3 (lambda and volts)"},
  {pid: 0x3B, text: "O2 sensor (extended range) bank 2, sensor 4 (lambda and volts)"},
  {pid: 0x3C, text: "Catalyst temperature in Â°C bank 1, sensor 1"},
  {pid: 0x3D, text: "Catalyst temperature in Â°C bank 2, sensor 1"},
  {pid: 0x3E, text: "Catalyst temperature in Â°C bank 1, sensor 2"},
  {pid: 0x3F, text: "Catalyst temperature in Â°C bank 2, sensor 1"},
  {pid: 0x40, text: "List of PIDs supported (range 65 to 96)"},
  {pid: 0x41, text: "Monitor status this drive cycle"},
  {pid: 0x42, text: "Control module voltage in V"},
  {pid: 0x43, text: "Absolute engine load"},
  {pid: 0x44, text: "Equivalent fuel/air mixture request"},
  {pid: 0x45, text: "Relative throttle position in %"},
  {pid: 0x46, text: "Ambient air temperature in Â°C"},
  {pid: 0x47, text: "Absolute throttle position B in %"},
  {pid: 0x48, text: "Absolute throttle position C in %"},
  {pid: 0x49, text: "Accelerator pedal position D in %"},
  {pid: 0x4A, text: "Accelerator pedal position E in %"},
  {pid: 0x4B, text: "Accelerator pedal position F in %"},
  {pid: 0x4C, text: "Commanded throttle actuator in %"},
  {pid: 0x4D, text: "Engine run time since MIL on in min"},
  {pid: 0x4E, text: "Engine run time since faults cleared in min"},
  {pid: 0x4F, text: "Exteral test equipment no. 1 configuration information"},
  {pid: 0x50, text: "Exteral test equipment no. 2 configuration information"},
  {pid: 0x51, text: "Fuel type used by the vehicle"},
  {pid: 0x52, text: "Ethanol fuel %"},
  {pid: 0x53, text: "Absolute evaporation system vapour pressure in kPa"},
  {pid: 0x54, text: "Evaporation system vapour pressure in Pa"},
  {pid: 0x55, text: "Short-term O2 sensor trim bank 1 and 3"},
  {pid: 0x56, text: "Long-term O2 sensor trim bank 1 and 3"},
  {pid: 0x57, text: "Short-term O2 sensor trim bank 2 and 4"},
  {pid: 0x58, text: "Long-term O2 sensor trim bank 2 and 4"},
  {pid: 0x59, text: "Absolute fuel rail pressure in kPa"},
  {pid: 0x5A, text: "Relative accelerator pedal position in %"},
  {pid: 0x5B, text: "Battery unit remaining life (hybrid) in %"},
  {pid: 0x5C, text: "Engine oil temperature in Â°C"},
  {pid: 0x5D, text: "Fuel injection timing in Â°"},
  {pid: 0x5E, text: "Fuel consumption in litre/hr"},
  {pid: 0x5F, text: "Fuel consumption in litre/hr"},
  {pid: 0x60, text: "List of PIDs supported (range 97 to 128)"},
  {pid: 0x61, text: "Driver demand: torque percentage (%)"},
  {pid: 0x62, text: "Final engine torque percentage (%)"},
  {pid: 0x63, text: "Engine torque reference in Nm"},
  {pid: 0x64, text: "Engine torque data in %"},
  {pid: 0x65, text: "Auxiliary inputs / outputs"},
  {pid: 0x66, text: "Flowmeter sensor"},
  {pid: 0x67, text: "Engine water temperature in Â°C"},
  {pid: 0x68, text: "Air temperature sensor in Â°C"},
  {pid: 0x69, text: "Commanded EGR and EGR error"},
  {pid: 0x6A, text: "Commanded Diesel intake air flow control and relative intake air flow position"},
  {pid: 0x6B, text: "Recirculation gas temperature in Â°C"},
  {pid: 0x6C, text: "Commanded throttle actuator control and relative throttle position"},
  {pid: 0x6D, text: "Fuel pressure control system"},
  {pid: 0x6E, text: "Injection pressure control system"},
  {pid: 0x6F, text: "Turbocharger compressor inlet pressure in kPa"},
  {pid: 0x70, text: "Boost pressure control in kPa"},
  {pid: 0x71, text: "Variable Geometry turbo (VGT) control"},
  {pid: 0x72, text: "Wastegate control"},
  {pid: 0x73, text: "Exhaust pressure in kPa"},
  {pid: 0x74, text: "Turbocharger RPM"},
  {pid: 0x75, text: "Turbocharger A temperature in Â°C"},
  {pid: 0x76, text: "Turbocharger B temperature in Â°C"},
  {pid: 0x77, text: "Charge air cooler temperature in Â°C"},
  {pid: 0x78, text: "Exhaust Gas temperature (EGT) Bank 1"},
  {pid: 0x79, text: "Exhaust Gas temperature (EGT) Bank 2"},
  {pid: 0x7A, text: "Diesel particulate filter (DPF) bank 1"},
  {pid: 0x7B, text: "Diesel particulate filter (DPF) bank 2"},
  {pid: 0x7C, text: "Diesel Particulate filter (DPF) temperature"},
  {pid: 0x7D, text: "NOx NTE control area status"},
  {pid: 0x7E, text: "PM NTE control area status"},
  {pid: 0x7F, text: "Engine run time"},
  {pid: 0x80, text: "List of PIDs supported (range 129 to 160)"}
],
[
  {pid: 0x00, text: "List of PIDs supported (range 01 to 32)"},
  {pid: 0x01, text: "Status since the last clearing of fault codes"},
  {pid: 0x02, text: "Fault code that caused the recording of \"freeze frame\" data"},
  {pid: 0x03, text: "Fuel system status"},
  {pid: 0x04, text: "Engine load calculated in %"},
  {pid: 0x05, text: "Temperature of the engine coolant in Â°C"},
  {pid: 0x06, text: "Short-term fuel % trim bank 1"},
  {pid: 0x07, text: "Long-term fuel % trim bank 1"},
  {pid: 0x08, text: "Short-term fuel % trim bank 2"},
  {pid: 0x09, text: "Long-term fuel % trim bank 2"},
  {pid: 0x0A, text: "Fuel pressure in kPa"},
  {pid: 0x0B, text: "Intake manifold absolute pressure in kPa"},
  {pid: 0x0C, text: "Engine speed in rpm"},
  {pid: 0x0D, text: "Vehicle speed in kph"},
  {pid: 0x0E, text: "Timing advance on cylinder 1 in degrees"},
  {pid: 0x0F, text: "Intake air temperature in Â°C"},
  {pid: 0x10, text: "Air flow measured by the flowmeter in g/s"},
  {pid: 0x11, text: "Throttle position in %"},
  {pid: 0x12, text: "Status of the secondary intake circuit"},
  {pid: 0x13, text: "O2 sensor positions bank/sensor"},
  {pid: 0x14, text: "Oxygen sensor volts bank 1 sensor 1/td>"},
  {pid: 0x15, text: "Oxygen sensor volts bank 1 sensor 2"},
  {pid: 0x16, text: "Oxygen sensor volts bank 1 sensor 3"},
  {pid: 0x17, text: "Oxygen sensor volts bank 1 sensor 4"},
  {pid: 0x18, text: "Oxygen sensor volts bank 2 sensor 1"},
  {pid: 0x19, text: "Oxygen sensor volts bank 2 sensor 2"},
  {pid: 0x1A, text: "Oxygen sensor volts bank 2 sensor 3"},
  {pid: 0x1B, text: "Oxygen sensor volts bank 2 sensor 4"},
  {pid: 0x1C, text: "OBD computer specification"},
  {pid: 0x1D, text: "O2 sensor positions bank/sensor"},
  {pid: 0x1E, text: "Auxiliary input status"},
  {pid: 0x1F, text: "Run time since engine start"},
  {pid: 0x20, text: "List of PIDs supported (range 33 to 64)"},
  {pid: 0x21, text: "Distance travelled with MIL on in kms"},
  {pid: 0x22, text: "Relative fuel rail pressure in kPa"},
  {pid: 0x23, text: "Fuel rail pressure in kPa"},
  {pid: 0x24, text: "O2 sensor (extended range) bank 1, sensor 1 (lambda and volts)"},
  {pid: 0x25, text: "O2 sensor (extended range) bank 1, sensor 2 (lambda and volts)"},
  {pid: 0x26, text: "O2 sensor (extended range) bank 1, sensor 3 (lambda and volts)"},
  {pid: 0x27, text: "O2 sensor (extended range) bank 1, sensor 4 (lambda and volts)"},
  {pid: 0x28, text: "O2 sensor (extended range) bank 2, sensor 1 (lambda and volts)"},
  {pid: 0x29, text: "O2 sensor (extended range) bank 2, sensor 2 (lambda and volts)"},
  {pid: 0x2A, text: "O2 sensor (extended range) bank 2, sensor 3 (lambda and volts)"},
  {pid: 0x2B, text: "O2 sensor (extended range) bank 2, sensor 4 (lambda and volts)"},
  {pid: 0x2C, text: "EGR in %"},
  {pid: 0x2D, text: "EGR error in %"},
  {pid: 0x2E, text: "Evaporation purge in %"},
  {pid: 0x2F, text: "Fuel level in %"},
  {pid: 0x30, text: "Number of warning(s) since faults (DTC) were cleared"},
  {pid: 0x31, text: "Distance since faults (DTC) were cleared."},
  {pid: 0x32, text: "Evaporation system vapour pressure in Pa"},
  {pid: 0x33, text: "Barometic pressure in kPa"},
  {pid: 0x34, text: "O2 sensor (extended range) bank 1, sensor 1 (lambda and volts)"},
  {pid: 0x35, text: "O2 sensor (extended range) bank 1, sensor 2 (lambda and volts)"},
  {pid: 0x36, text: "O2 sensor (extended range) bank 1, sensor 3 (lambda and volts)"},
  {pid: 0x37, text: "O2 sensor (extended range) bank 1, sensor 4 (lambda and volts)"},
  {pid: 0x38, text: "O2 sensor (extended range) bank 2, sensor 1 (lambda and volts)"},
  {pid: 0x39, text: "O2 sensor (extended range) bank 2, sensor 2 (lambda and volts)"},
  {pid: 0x3A, text: "O2 sensor (extended range) bank 2, sensor 3 (lambda and volts)"},
  {pid: 0x3B, text: "O2 sensor (extended range) bank 2, sensor 4 (lambda and volts)"},
  {pid: 0x3C, text: "Catalyst temperature in Â°C bank 1, sensor 1"},
  {pid: 0x3D, text: "Catalyst temperature in Â°C bank 2, sensor 1"},
  {pid: 0x3E, text: "Catalyst temperature in Â°C bank 1, sensor 2"},
  {pid: 0x3F, text: "Catalyst temperature in Â°C bank 2, sensor 1"},
  {pid: 0x40, text: "List of PIDs supported (range 65 to 96)"},
  {pid: 0x41, text: "Monitor status this drive cycle"},
  {pid: 0x42, text: "Control module voltage in V"},
  {pid: 0x43, text: "Absolute engine load"},
  {pid: 0x44, text: "Equivalent fuel/air mixture request"},
  {pid: 0x45, text: "Relative throttle position in %"},
  {pid: 0x46, text: "Ambient air temperature in Â°C"},
  {pid: 0x47, text: "Absolute throttle position B in %"},
  {pid: 0x48, text: "Absolute throttle position C in %"},
  {pid: 0x49, text: "Accelerator pedal position D in %"},
  {pid: 0x4A, text: "Accelerator pedal position E in %"},
  {pid: 0x4B, text: "Accelerator pedal position F in %"},
  {pid: 0x4C, text: "Commanded throttle actuator in %"},
  {pid: 0x4D, text: "Engine run time since MIL on in min"},
  {pid: 0x4E, text: "Engine run time since faults cleared in min"},
  {pid: 0x4F, text: "Exteral test equipment no. 1 configuration information"},
  {pid: 0x50, text: "Exteral test equipment no. 2 configuration information"},
  {pid: 0x51, text: "Fuel type used by the vehicle"},
  {pid: 0x52, text: "Ethanol fuel %"},
  {pid: 0x53, text: "Absolute evaporation system vapour pressure in kPa"},
  {pid: 0x54, text: "Evaporation system vapour pressure in Pa"},
  {pid: 0x55, text: "Short-term O2 sensor trim bank 1 and 3"},
  {pid: 0x56, text: "Long-term O2 sensor trim bank 1 and 3"},
  {pid: 0x57, text: "Short-term O2 sensor trim bank 2 and 4"},
  {pid: 0x58, text: "Long-term O2 sensor trim bank 2 and 4"},
  {pid: 0x59, text: "Absolute fuel rail pressure in kPa"},
  {pid: 0x5A, text: "Relative accelerator pedal position in %"},
  {pid: 0x5B, text: "Battery unit remaining life (hybrid) in %"},
  {pid: 0x5C, text: "Engine oil temperature in Â°C"},
  {pid: 0x5D, text: "Fuel injection timing in Â°"},
  {pid: 0x5E, text: "Fuel consumption in litre/hr"},
  {pid: 0x5F, text: "Fuel consumption in litre/hr"},
  {pid: 0x60, text: "List of PIDs supported (range 97 to 128)"},
  {pid: 0x61, text: "Driver demand: torque percentage (%)"},
  {pid: 0x62, text: "Final engine torque percentage (%)"},
  {pid: 0x63, text: "Engine torque reference in Nm"},
  {pid: 0x64, text: "Engine torque data in %"},
  {pid: 0x65, text: "Auxiliary inputs / outputs"},
  {pid: 0x66, text: "Flowmeter sensor"},
  {pid: 0x67, text: "Engine water temperature in Â°C"},
  {pid: 0x68, text: "Air temperature sensor in Â°C"},
  {pid: 0x69, text: "Commanded EGR and EGR error"},
  {pid: 0x6A, text: "Commanded Diesel intake air flow control and relative intake air flow position"},
  {pid: 0x6B, text: "Recirculation gas temperature in Â°C"},
  {pid: 0x6C, text: "Commanded throttle actuator control and relative throttle position"},
  {pid: 0x6D, text: "Fuel pressure control system"},
  {pid: 0x6E, text: "Injection pressure control system"},
  {pid: 0x6F, text: "Turbocharger compressor inlet pressure in kPa"},
  {pid: 0x70, text: "Boost pressure control in kPa"},
  {pid: 0x71, text: "Variable Geometry turbo (VGT) control"},
  {pid: 0x72, text: "Wastegate control"},
  {pid: 0x73, text: "Exhaust pressure in kPa"},
  {pid: 0x74, text: "Turbocharger RPM"},
  {pid: 0x75, text: "Turbocharger A temperature in Â°C"},
  {pid: 0x76, text: "Turbocharger B temperature in Â°C"},
  {pid: 0x77, text: "Charge air cooler temperature in Â°C"},
  {pid: 0x78, text: "Exhaust Gas temperature (EGT) Bank 1"},
  {pid: 0x79, text: "Exhaust Gas temperature (EGT) Bank 2"},
  {pid: 0x7A, text: "Diesel particulate filter (DPF) bank 1"},
  {pid: 0x7B, text: "Diesel particulate filter (DPF) bank 2"},
  {pid: 0x7C, text: "Diesel Particulate filter (DPF) temperature"},
  {pid: 0x7D, text: "NOx NTE control area status"},
  {pid: 0x7E, text: "PM NTE control area status"},
  {pid: 0x7F, text: "Engine run time"},
  {pid: 0x80, text: "List of PIDs supported (range 129 to 160)"},
],
[],
[],
[
  {pid: 0x00, text: "List of PIDs supported (range 01 to 32)"},
  {pid: 0x01, text: "Rich to lean sensor threshold voltage"},
  {pid: 0x02, text: "Lean to rich sensor threshold voltage"},
  {pid: 0x03, text: "Low voltage used to calculated passage time"},
  {pid: 0x04, text: "High voltage used to calculated passage time"},
  {pid: 0x05, text: "Rich to lean calculated passage time"},
  {pid: 0x06, text: "Lean to rich calculated passage time"},
  {pid: 0x07, text: "Minimum sensor voltage during test cycle"},
  {pid: 0x08, text: "Maximum sensor voltage during test cycle"},
  {pid: 0x09, text: "Time between sensor transitions"},
  {pid: 0x0A, text: "Sensor period"},
  {pid: 0x0B, text: "Reserved for future use"},
],
[
  {pid: 0x00, text: "List of PIDs supported (range 01h to 20h)"},
  {pid: 0x01, text: "Exhaust gas sensor bank 1 - sensor 1"},
  {pid: 0x02, text: "Exhaust gas sensor bank 1 - sensor 2"},
  {pid: 0x03, text: "Exhaust gas sensor bank 1 - sensor 3"},
  {pid: 0x04, text: "Exhaust gas sensor bank 1 - sensor 4"},
  {pid: 0x05, text: "Exhaust gas sensor bank 2 - sensor 1"},
  {pid: 0x06, text: "Exhaust gas sensor bank 2 - sensor 2"},
  {pid: 0x07, text: "Exhaust gas sensor bank 2 - sensor 3"},
  {pid: 0x08, text: "Exhaust gas sensor bank 2 - sensor 4"},
  {pid: 0x09, text: "Exhaust gas sensor bank 3 - sensor 1"},
  {pid: 0x0A, text: "Exhaust gas sensor bank 3 - sensor 2"},
  {pid: 0x0B, text: "Exhaust gas sensor bank 3 - sensor 3"},
  {pid: 0x0C, text: "Exhaust gas sensor bank 3 - sensor 4"},
  {pid: 0x0D, text: "Exhaust gas sensor bank 4 - sensor 1"},
  {pid: 0x0E, text: "Exhaust gas sensor bank 4 - sensor 2"},
  {pid: 0x0F, text: "Exhaust gas sensor bank 4 - sensor 3"},
  {pid: 0x10, text: "Exhaust gas sensor bank 4 - sensor 4"},
  {pid: 0x20, text: "List of PIDs supported (range 21h to 40h)"},
  {pid: 0x21, text: "Catalytic bank 1"},
  {pid: 0x22, text: "Catalytic bank 2"},
  {pid: 0x23, text: "Catalytic bank 3"},
  {pid: 0x24, text: "Catalytic bank 4"},
  {pid: 0x31, text: "EGR bank 1"},
  {pid: 0x32, text: "EGR bank 2"},
  {pid: 0x33, text: "EGR bank 3"},
  {pid: 0x34, text: "EGR bank 4"},
  {pid: 0x35, text: "VVT bank 1"},
  {pid: 0x36, text: "VVT bank 2"},
  {pid: 0x37, text: "VVT bank 3"},
  {pid: 0x38, text: "VVT bank 4"},
  {pid: 0x39, text: "EVAP (Cap Off / 0.150\")"},
  {pid: 0x3A, text: "EVAP (0.090\")"},
  {pid: 0x3B, text: "EVAP (0.040\")"},
  {pid: 0x3C, text: "EVAP (0.020\")"},
  {pid: 0x3D, text: "Flux de purge"},
  {pid: 0x40, text: "List of PIDs supported (range 41h to 60h)"},
  {pid: 0x41, text: "Heated exhaust gas sensor bank 1 - sensor 1"},
  {pid: 0x42, text: "Heated exhaust gas sensor bank 1 - sensor 2"},
  {pid: 0x43, text: "Heated exhaust gas sensor bank 1 - sensor 3"},
  {pid: 0x44, text: "Heated exhaust gas sensor bank 1 - sensor 4"},
  {pid: 0x45, text: "Heated exhaust gas sensor bank 2 - sensor 1"},
  {pid: 0x46, text: "Heated exhaust gas sensor bank 2 - sensor 2"},
  {pid: 0x47, text: "Heated exhaust gas sensor bank 2 - sensor 3"},
  {pid: 0x48, text: "Heated exhaust gas sensor bank 2 - sensor 4"},
  {pid: 0x49, text: "Heated exhaust gas sensor bank 3 - sensor 1"},
  {pid: 0x4A, text: "Heated exhaust gas sensor bank 3 - sensor 2"},
  {pid: 0x4B, text: "Heated exhaust gas sensor bank 3 - sensor 3"},
  {pid: 0x4C, text: "Heated exhaust gas sensor bank 3 - sensor 4"},
  {pid: 0x4D, text: "Heated exhaust gas sensor bank 4 - sensor 1"},
  {pid: 0x4E, text: "Heated exhaust gas sensor bank 4 - sensor 2"},
  {pid: 0x4F, text: "Heated exhaust gas sensor bank 4 - sensor 3"},
  {pid: 0x50, text: "Heated exhaust gas sensor bank 4 - sensor 4"},
  {pid: 0x60, text: "List of PIDs supported (range 61h to 80h)"},
  {pid: 0x61, text: "Heated catalyst bank 1"},
  {pid: 0x62, text: "Heated catalyst bank 2"},
  {pid: 0x63, text: "Heated catalyst bank 3"},
  {pid: 0x64, text: "Heated catalyst bank 4"},
  {pid: 0x71, text: "Secondary air 1"},
  {pid: 0x72, text: "Secondary air 2"},
  {pid: 0x73, text: "Secondary air 3"},
  {pid: 0x74, text: "Secondary air 4"},
  {pid: 0x80, text: "List of PIDs supported (range 81h to A0h)"},
  {pid: 0x81, text: "Fuel system bank 1"},
  {pid: 0x82, text: "Fuel system bank 2"},
  {pid: 0x83, text: "Fuel system bank 3"},
  {pid: 0x84, text: "Fuel system bank 4"},
  {pid: 0x85, text: "Turbo pressure bank 1"},
  {pid: 0x86, text: "Turbo pressure bank 2"},
  {pid: 0x90, text: "Nox Absorber bank 1"},
  {pid: 0x91, text: "Nox Absorber bank 2"},
  {pid: 0x98, text: "Catalytic NOx bank 1"},
  {pid: 0x99, text: "Catalytic NOx bank 2"},
  {pid: 0xA0, text: "List of PIDs supported (range A1h to C0h)"},
  {pid: 0xA1, text: "General misfire monitoring data"},
  {pid: 0xA2, text: "Misfire data cylinder 1"},
  {pid: 0xA3, text: "Misfire data cylinder 2"},
  {pid: 0xA4, text: "Misfire data cylinder 3"},
  {pid: 0xA5, text: "Misfire data cylinder 4"},
  {pid: 0xA6, text: "Misfire data cylinder 5"},
  {pid: 0xA7, text: "Misfire data cylinder 6"},
  {pid: 0xA8, text: "Misfire data cylinder 7"},
  {pid: 0xA9, text: "Misfire data cylinder 8"},
  {pid: 0xAA, text: "Misfire data cylinder 9"},
  {pid: 0xAB, text: "Misfire data cylinder 10"},
  {pid: 0xAC, text: "Misfire data cylinder 11"},
  {pid: 0xAD, text: "Misfire data cylinder 12"},
  {pid: 0xAE, text: "Misfire data cylinder 13"},
  {pid: 0xAF, text: "Misfire data cylinder 14"},
  {pid: 0xB0, text: "Misfire data cylinder 15"},
  {pid: 0xB1, text: "Misfire data cylinder 16"},
  {pid: 0xB2, text: "PM filter bank 1"},
  {pid: 0xB3, text: "PM filter bank 2"},
  {pid: 0xC0, text: "List of PIDs supported (range C1h to E0h)"},
  {pid: 0xE0, text: "List of PIDs supported (range E1h to FFh)"},
],
[],
[],
[
  {pid: 0x00, text: "List of PIDs supported (range 01h to 20h)"},
  {pid: 0x01, text: "VIN message count"},
  {pid: 0x02, text: "VIN (vehicle identification number)"},
  {pid: 0x03, text: "Calibration ID message count"},
  {pid: 0x04, text: "Calibration IDs"},
  {pid: 0x05, text: "CALIB verification numbers message count"},
  {pid: 0x06, text: "Calibration verification number"},
  {pid: 0x07, text: "IPT message count"},
  {pid: 0x08, text: "In-use performance tracking (IPT)"},
  {pid: 0x09, text: "ECU name message count"},
  {pid: 0x0A, text: "ECU name"},
  {pid: 0x0B, text: "In-use performance tracking"},
]
];
